<a href="https://colab.research.google.com/github/EduardoLawson1/Pytorch_Fundamentals/blob/main/Pytorch00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu118


In [ ]:
torch.range(0,10)

<ipython-input-2-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
# TENSOR
TENSOR = torch.tensor([[1,2 ,3],
                        ])
TENSOR

tensor([[1, 2, 3]])

In [ ]:
TENSOR.ndim

2

In [ ]:
TENSOR.shape

torch.Size([1, 3])

In [ ]:
#criando um tensor aleatório de shape ou tamanho(3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3809, 0.3456, 0.5308, 0.1861],
        [0.6762, 0.2340, 0.0455, 0.8579],
        [0.8082, 0.4705, 0.9906, 0.7079]])

In [ ]:
#criando um tenosr com shape similiar a imagem
random_image_size_tensor = torch.rand(size=(224, 224, 3))#altura, largura, canais de cores
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_tensor.ndim

2

In [ ]:
x_original = torch.rand(size=(224, 224, 3))
# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
x_original[0, 0, 0] = 123
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")
print(f"Value of [0,0,0]: {x_permuted[0, 0, 0]}")

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
#x, x.shape
#x[0][2][2]
x[:, :, 2]

tensor([[3, 6, 9]])

In [ ]:
!nvidia-smi

Mon Nov 27 18:19:41 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   59C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
torch.cuda.is_available()

True

In [ ]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')